site_name: Selectpicker
site_description: A simple javascript selectpicker.
repo_url: https://github.com/NoxRacing/Selectpicker
theme: jekyll-theme-cayman
extra_css:
- css/custom.css
- dist/css/selectpicker.css
extra_javascript:
- dist/js/selectpicker.js
pages:
- Selectpicker: index.md
- Methods: methods.md
- Examples: examples.md
extra:
version: 1.0.0
